// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: simplePool.proto

package simplePool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimplePool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceType string `protobuf:"bytes,1,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	PoolId       string `protobuf:"bytes,2,opt,name=poolId,proto3" json:"poolId,omitempty"`
	Subnet       string `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	//map<string, PoolItem> itemsReserved = 6;
	ItemsUsed map[string]*PoolItem `protobuf:"bytes,7,rep,name=itemsUsed,proto3" json:"itemsUsed,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SimplePool) Reset() {
	*x = SimplePool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simplePool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimplePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplePool) ProtoMessage() {}

func (x *SimplePool) ProtoReflect() protoreflect.Message {
	mi := &file_simplePool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplePool.ProtoReflect.Descriptor instead.
func (*SimplePool) Descriptor() ([]byte, []int) {
	return file_simplePool_proto_rawDescGZIP(), []int{0}
}

func (x *SimplePool) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *SimplePool) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *SimplePool) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *SimplePool) GetItemsUsed() map[string]*PoolItem {
	if x != nil {
		return x.ItemsUsed
	}
	return nil
}

type PoolItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Metadata string `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *PoolItem) Reset() {
	*x = PoolItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simplePool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolItem) ProtoMessage() {}

func (x *PoolItem) ProtoReflect() protoreflect.Message {
	mi := &file_simplePool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolItem.ProtoReflect.Descriptor instead.
func (*PoolItem) Descriptor() ([]byte, []int) {
	return file_simplePool_proto_rawDescGZIP(), []int{1}
}

func (x *PoolItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PoolItem) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_simplePool_proto protoreflect.FileDescriptor

var file_simplePool_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x22, 0xf9,
	0x01, 0x0a, 0x0a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62,
	0x6e, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x12, 0x43, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x55, 0x73, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x6f, 0x6f,
	0x6c, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x55, 0x73, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x55, 0x73, 0x65, 0x64, 0x1a, 0x52, 0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x55,
	0x73, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3c, 0x0a, 0x08, 0x50, 0x6f,
	0x6f, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x73, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simplePool_proto_rawDescOnce sync.Once
	file_simplePool_proto_rawDescData = file_simplePool_proto_rawDesc
)

func file_simplePool_proto_rawDescGZIP() []byte {
	file_simplePool_proto_rawDescOnce.Do(func() {
		file_simplePool_proto_rawDescData = protoimpl.X.CompressGZIP(file_simplePool_proto_rawDescData)
	})
	return file_simplePool_proto_rawDescData
}

var file_simplePool_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_simplePool_proto_goTypes = []interface{}{
	(*SimplePool)(nil), // 0: simplePool.SimplePool
	(*PoolItem)(nil),   // 1: simplePool.PoolItem
	nil,                // 2: simplePool.SimplePool.ItemsUsedEntry
}
var file_simplePool_proto_depIdxs = []int32{
	2, // 0: simplePool.SimplePool.itemsUsed:type_name -> simplePool.SimplePool.ItemsUsedEntry
	1, // 1: simplePool.SimplePool.ItemsUsedEntry.value:type_name -> simplePool.PoolItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_simplePool_proto_init() }
func file_simplePool_proto_init() {
	if File_simplePool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simplePool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimplePool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simplePool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simplePool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simplePool_proto_goTypes,
		DependencyIndexes: file_simplePool_proto_depIdxs,
		MessageInfos:      file_simplePool_proto_msgTypes,
	}.Build()
	File_simplePool_proto = out.File
	file_simplePool_proto_rawDesc = nil
	file_simplePool_proto_goTypes = nil
	file_simplePool_proto_depIdxs = nil
}
